version: "3.4"

services:
  client:
    image: registry.cn-hangzhou.aliyuncs.com/acblog/wasm-host:latest
    ports:
      - "6000:80"
    volumes:
      - ./client/appsettings.json:/app/appsettings.json
      - ./client/manifest.json:/app/wwwroot/manifest.json
      - ./client/background.jpg:/app/wwwroot/background.jpg
      - ./client/icon.png:/app/wwwroot/icon.png
    depends_on:
      - api
  api:
    image: registry.cn-hangzhou.aliyuncs.com/acblog/api:latest
    ports:
      - "6100:80"
    environment:
      - ConnectionStrings:IdentityConnection=Server=db;User=sa;Password=MyPassword001;Database=api_identity;
      - ConnectionStrings:DefaultConnection=Server=db;User=sa;Password=MyPassword001;Database=api_default;
      - LomentServer:Uri=http://loment
      - LomentServer:Enable=true
    volumes:
      - ./api/appsettings.json:/app/appsettings.json
    depends_on:
      - db
      - server
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=MyPassword001
      - ACCEPT_EULA=Y
    volumes:
      - data:/var/opt/mssql
  loment:
    image: registry.cn-hangzhou.aliyuncs.com/stardustdl/loment:latest # stardustdl/loment:latest
    environment:
      - LOMENT_DBORIGIN=root:123456@(lomentdb:3306)
      - LOMENT_DBNAME=loment_db
    depends_on:
      - lomentdb
  lomentdb:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    security_opt:
      - seccomp:unconfined
    volumes:
      - lomentdata:/var/opt/mssql
volumes:
  data:
  lomentdata: