name: CD-Preview

on:
  repository_dispatch:
    types: [cd-preview]

defaults:
  run:
    shell: pwsh

env:
  dotnet-version: "5.0.100-rc.2.20479.15"
  node-version: "12.x"
  build_version: "0.0.3.${{ github.run_number }}-preview1"

jobs:
  pub-images-packages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.dotnet-version }}
    - name: Setup NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.node-version }}
    - name: Setup psake
      run: Set-PSRepository -Name PSGallery -InstallationPolicy Trusted; Install-Module -Name psake
    - name: CD
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.AZ_TOKEN }}
      run: Invoke-psake cd
    - name: Push Client.WebAssembly image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.MIRROR_DOCKER_USERNAME }}
        password: ${{ secrets.MIRROR_DOCKER_PASSWORD }}
        registry: registry.cn-hangzhou.aliyuncs.com
        repository: stardustdl/acblog-preview
        tags: wasm
        dockerfile: ./src/client/AcBlog.Client.WebAssembly/Dockerfile
    - name: Push Client.WebAssembly.Host image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.MIRROR_DOCKER_USERNAME }}
        password: ${{ secrets.MIRROR_DOCKER_PASSWORD }}
        registry: registry.cn-hangzhou.aliyuncs.com
        repository: stardustdl/acblog-preview
        tags: wasm-host
        dockerfile: ./src/client/AcBlog.Client.WebAssembly.Host/Dockerfile
    - name: Push Client.Server image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.MIRROR_DOCKER_USERNAME }}
        password: ${{ secrets.MIRROR_DOCKER_PASSWORD }}
        registry: registry.cn-hangzhou.aliyuncs.com
        repository: stardustdl/acblog-preview
        tags: client
        dockerfile: ./src/client/AcBlog.Client.Server/Dockerfile
    - name: Push Server.Api image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.MIRROR_DOCKER_USERNAME }}
        password: ${{ secrets.MIRROR_DOCKER_PASSWORD }}
        registry: registry.cn-hangzhou.aliyuncs.com
        repository: stardustdl/acblog-preview
        tags: api
        dockerfile: ./src/AcBlog.Server.Api/Dockerfile
    - name: Upload package artifacts
      uses: actions/upload-artifact@v2
      with:
        name: packages
        path: ./packages
    - name: Upload WASM artifacts
      uses: actions/upload-artifact@v2
      with:
        name: wasm
        path: ./src/client/AcBlog.Client.WebAssembly/publish